// File: LightingData.js

const fixtureOptions = {
    Bulbs: [
      { label: "2’ PL Biax Bulb", wattage: 23 },
      { label: "2-Pin CFL Bulb", wattage: 13 },
      { label: "4-Pin CFL Bulb", wattage: 23 },
      { label: "A19 FL Bulb", wattage: 12 },
      { label: "A19 LED Bulb", wattage: 9 },
      { label: "BR30 LED Bulb", wattage: 12 },
      { label: "G25 LED Bulb", wattage: 7 },
      { label: "G8 LED Bulb", wattage: 6 },
      { label: "G9 Halogen Bulb", wattage: 40 },
      { label: "Globe LED A-Base Bulb", wattage: 9 },
      { label: "Highbay LED Screw in Bulb", wattage: 50 },
      { label: "Incadescent Bulb - 100", wattage: 100 },
      { label: "Incadescent Bulb - 60", wattage: 60 },
      { label: "LED Corn Bulb", wattage: 25 },
      { label: "LED HID Retrofit Bulb", wattage: 20 },
      { label: "MR16 LED Bulb", wattage: 7 },
      { label: "PAR30/38 LED Bulb", wattage: 13 },
      { label: "R20 LED Bulb", wattage: 7 },
      { label: "T10 E26 LED Bulb", wattage: 7 },
      { label: "Other LED Bulb", wattage: null },
      { label: "Other FL Bulb", wattage: null },
      { label: "Other CFL Bulb", wattage: null },
      { label: "Other Incadescent Bulb", wattage: null },
      { label: "Other Halogen Bulb", wattage: null },
    ],
    "Strip & Tube Lights": [
      { label: "2' LED Strip / Tube", wattage: 12 },
      { label: "2' T12 Tube", wattage: 25 },
      { label: "2' T8 Tube", wattage: 16 },
      { label: "3’ LED Strip", wattage: 25 },
      { label: "3’ T12 Tube", wattage: 40 },
      { label: "4' LED Strip / Tube", wattage: 16 },
      { label: "4' T12 Tube", wattage: 50 },
      { label: "4' T8 Tube", wattage: 30 },
      { label: "8' LED Tube", wattage: 30 },
      { label: "8' T12 Tube", wattage: 90 },
      { label: "8' T8 Tube", wattage: 65 },
      { label: "Other Tube Lights", wattage: null },
    ],
    "Ceiling Mounted Lights": [
      { label: "12” Circline LED", wattage: 16 },
      { label: "1x4 LED Panel", wattage: 30 },
      { label: "2x2 Flat Panel with U Shaped FL bulb", wattage: 70 },
      { label: "2x2 LED Troffer", wattage: 30 },
      { label: "2x4 FL 4 tube", wattage: 128 },
      { label: "2x4 LED Troffer", wattage: 50 },
      { label: "2x4 Recessed LED lighting", wattage: 40 },
      { label: '4" LED High Hat', wattage: 12 },
      { label: '4" Squares LED', wattage: 15 },
      { label: '4” High Hat w/ MR16 LED', wattage: 9 },
      { label: '4” square can PAR30 LED', wattage: 11 },
      { label: '5" High Hat', wattage: 15 },
      { label: '6" Cans with R20 LED', wattage: 8 },
      { label: '6" High Hat LED', wattage: 15 },
      { label: '6” Can with A19 LED', wattage: 9 },
      { label: '6” Can with BR30 LED', wattage: 15 },
      { label: '6” Flush Mount LED', wattage: 12 },
      { label: '6” Ultra Thin Downlight LED Flush Mount', wattage: 9 },
      { label: '6”x2’ LED Panel', wattage: 13 },
      { label: '8" flush mount LED', wattage: 15 },
      { label: 'Flush mount 10" LED', wattage: 20 },
      { label: 'Flush Mount 12" Fl', wattage: 16 },
      { label: 'Flush Mount LED with Aircraft Chains', wattage: 15 },
      { label: 'Other Ceiling Mounted Lights', wattage: null },
    ],
    "Wall Mounted Lights": [
      { label: "Wall mounted Fixture with CFL Bulb", wattage: 13 },
      { label: "Wall Mounted LED", wattage: 12 },
      { label: "Wall Pack LED", wattage: 25 },
      { label: "Wall sconce CFL Bulbs", wattage: 26 },
      { label: "Wall sconce FL Bulbs", wattage: 25 },
      { label: "Wall sconce LED", wattage: 15 },
      { label: "Wall Sconce PL LED Bulb", wattage: 13 },
      { label: "Wall sconce with A19 LED", wattage: 10 },
      { label: "Wall Sconce with B11 LED Bulbs", wattage: 6 },
      { label: "Wall Sconce with Candelabra Base LED", wattage: 5 },
      { label: "Wall sconce with Halogen", wattage: 38 },
      { label: "Wall Sconce with LED Strip", wattage: 9 },
      { label: "Wall Wash LED", wattage: 15 },
      { label: "Other Wall Mounted Light", wattage: null },
    ],
    "Other Lights": [
      { label: "Box mount fixture A Lamp LED", wattage: 9 },
      { label: "Cove lighting (MR16)", wattage: 7 },
      { label: "Cove lighting T5 LED Tubes", wattage: 22 },
      { label: "Custom Arch Globe Light", wattage: 15 },
      { label: "Custom Cove LED Strip (per ft)", wattage: 1.5 },
      { label: "Exit sign LED", wattage: 5 },
      { label: "Glass pendant lamp with LED Integrated", wattage: 12 },
      { label: "Inground LED Light", wattage: 6 },
      { label: "LED Flood Light", wattage: 20 },
      { label: "LED Stick PL", wattage: 14 },
      { label: "PAR30 Spotlight", wattage: 12 },
      { label: "Spotlight LED", wattage: 10 },
      { label: "Other Light", wattage: null },
    ],
  };
  
  export default fixtureOptions;
  